#!/usr/bin/env python3
"""Keep README.md's version/latest-change block current, from the source of truth.

The README's prose is hand-written and version-agnostic on purpose; its book links point
at `blob/main/*.pdf` and the app link at `/releases/latest`, so they never go stale. The
one thing that *does* drift is the "current editions" line and the "latest change" note.
This script regenerates only the region between the AUTO markers, reading versions straight
from the build scripts and the app source, and the headline from CHANGELOG.md — so the
README always agrees with what actually shipped, and a human never has to remember to edit it.

Idempotent: running it twice makes no change. Wired to run on every commit by
`.githooks/pre-commit` (see CLAUDE.md). Safe to run by hand any time.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BEGIN = "<!-- AUTO:editions (regenerated by update_readme.py — do not edit by hand) -->"
END = "<!-- /AUTO:editions -->"


def _find(path: str, pattern: str) -> str | None:
    try:
        text = (ROOT / path).read_text(encoding="utf-8")
    except OSError:
        return None
    m = re.search(pattern, text)
    return m.group(1) if m else None


def current_versions() -> dict:
    """Read each component's version from the file that authoritatively carries it."""
    return {
        "Player's Book": _find("build_player.py", r"The Player's Book · Version ([\d.]+)"),
        "Keeper's Book": _find("build_keeper.py", r"The Keeper's Book · Version ([\d.]+)"),
        "Bestiary": _find("build_bestiary.py", r"The Bestiary · Version ([\d.]+)"),
        "GritKeeper": _find("GK/source/MainForm.cs", r'AppVersion\s*=\s*"([\d.]+)"'),
    }


def latest_change() -> str | None:
    """The headline of the newest CHANGELOG entry: the bold title, minus its (date, …) tail."""
    try:
        text = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")
    except OSError:
        return None
    body = text.split("\n---\n", 1)[-1]
    m = re.search(r"-\s+\*\*(.+?)\*\*", body, re.S)
    if not m:
        return None
    title = re.sub(r"\s+", " ", m.group(1)).strip()
    title = re.sub(r"\s*\([^)]*\)\s*\.?$", "", title).strip().rstrip(".")
    return title


def render_block() -> str:
    v = current_versions()
    editions = " · ".join(f"{name} v{ver}" for name, ver in v.items() if ver)
    lines = [BEGIN]
    if editions:
        lines.append(f"**Current editions** — {editions}.")
    change = latest_change()
    if change:
        lines.append("")
        lines.append(f"*Latest change:* {change}. See "
                     "[CHANGELOG.md](CHANGELOG.md) for the full record.")
    lines.append(END)
    return "\n".join(lines)


def update(readme: Path) -> bool:
    """Rewrite the AUTO block in place. Returns True if the file changed."""
    text = readme.read_text(encoding="utf-8")
    block = render_block()
    if BEGIN in text and END in text:
        new = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
    else:
        # first run: drop the block just after the one-line "three books and one app." pitch
        anchor = "off three books and one app.\n"
        idx = text.find(anchor)
        insert_at = idx + len(anchor) if idx != -1 else 0
        new = text[:insert_at] + "\n" + block + "\n" + text[insert_at:]
    if new == text:
        return False
    readme.write_text(new, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    readme = ROOT / "README.md"
    if not readme.exists():
        print("update_readme: README.md not found", file=sys.stderr)
        return 0  # never block a commit over this
    changed = update(readme)
    print("update_readme: README.md " + ("updated" if changed else "already current"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
